### PR TITLE
Merge Anchors on demand

### LINKED ISSUE #44: Using "<<: *link" syntax does no produce expected result
Hi.

I've faced with an issue with substitution one map keys an values into another one.

This syntax works correctly:
```elixir
yaml = """
  me: &link
    name: a
    id: 1
  other: *link
"""
# "me: &link\n  name: a\n  id: 1\nother: *link\n"
YamlElixir.read_from_string(yaml)
#{:ok, %{"me" => %{"id" => 1, "name" => "a"}, "other" => %{"id" => 1, "name" => "a"}}}
```

But this is not:
```elixir
yaml = """
  me: &link
    name: a
    id: 1
  other:
    <<: *link
    id: 2
"""
# "me: &link\n  name: a\n  id: 1\nother:\n  <<: *link\n  id: 2\n"

YamlElixir.read_from_string(yaml)
# {:ok,
#  %{
#    "me" => %{"id" => 1, "name" => "a"},
#    "other" => %{"<<" => %{"id" => 1, "name" => "a"}, "id" => 2}
#  }}
```
The expected result is substituting all key-values from `*link` into the second map. These keys can be update with new values, like `id` field in this example.
But instead it produces a nested map with "<<" key, and map merging does not work as expected.

This syntax is a part of YAML 1.1 standart:
https://yaml.org/type/merge.html
and is supported by a lot of libraries for other languages, such as Ruby (YAML module) and Python (pyyaml).

Could you please fix this behavior?

### PR DESCRIPTION
**Pull request by floriank**
Hey,

I currently work on a project which needs to read a bit of YAML (some OpenAPIv3 specifications) and ran into #44. While digging into the `yamerl` parsing, I concluded that the behaviour is actually correct, but a little unsatisfying to work with.

I've patched the lib to allow for using an option to automatically merge anchors if so desired.
```elixir
yaml = """
a: &a
  b: 42
c:
  <<: *a
  d: 43
"""
# this branch
{:ok, %{"a" => %{"b" => 42}, "c" => %{"b" => 42, "d" => 43}}} = 
  yaml |> YamlElixir.read_from_string(merge_anchors: true)

# current behaviour in main
{:ok, %{"a" => %{"b" => 42}, "c" => %{"<<" => %{"b" => 42}, "d" => 43}}} = 
  yaml |> YamlElixir.read_from_string(merge_anchors: false)
```

The old behaviour is completely intact and is still the default, as to not break any existing clients.

Do you need me to update the README/docs/CHANGELOG?

Thanks a ton for providing this library!

Fixes #44.

### CODE REVIEW

File: lib/yaml_elixir/mapper.ex [hunk 1]
```diff
@@ -6,6 +6,7 @@ defmodule YamlElixir.Mapper do
     yaml
     |> _to_map(options)
     |> extract_map(options)
+    |> merge_anchors(options)
```
Comment (KamilLelonek) [inline lib/yaml_elixir/mapper.ex]: I suggest naming this function `maybe_merge_anchors` since you are not always doing that there.

File: lib/yaml_elixir/mapper.ex [hunk 2]
```diff
@@ -93,4 +94,29 @@ defmodule YamlElixir.Mapper do
       _ -> &Map.put_new/3
     end
   end
+
+  defp merge_anchors(value, options) do
+    if options |> Keyword.get(:merge_anchors) do
```
Comment (KamilLelonek) [inline lib/yaml_elixir/mapper.ex]: There's no need to pipe just one argument. `Keyword.get(options, :merge_anchors)` is enough.

File: lib/yaml_elixir/mapper.ex [hunk 3]
```diff
@@ -93,4 +94,29 @@ defmodule YamlElixir.Mapper do
...
+      _merge_anchors(value)
```
Comment (KamilLelonek) [inline lib/yaml_elixir/mapper.ex]: This naming convention is not used in Elixir at all. If you name the parent function `maybe_merge_anchors`, you can name this one just `merge_anchors`.

File: lib/yaml_elixir/mapper.ex [hunk 4]
```diff
@@ -93,4 +94,29 @@ defmodule YamlElixir.Mapper do
...
+      value
+    end
+  end
+
+  defp _merge_anchors(value) when is_list(value), do: value |> Enum.map(&_merge_anchors/1)
+
+  defp _merge_anchors(map) when is_map(map) do
+    map
+    |> Enum.reduce(%{}, fn {k, v}, acc ->
+      if k == "<<" do
```
Comment (KamilLelonek) [inline lib/yaml_elixir/mapper.ex]: You can use `fn` pattern matching instead of these `ifs` again.

File: lib/yaml_elixir/mapper.ex [hunk 5]
```diff
@@ -93,4 +94,29 @@ defmodule YamlElixir.Mapper do
...
+        acc |> Map.merge(v)
+      else
+        acc |> Map.put(k, _merge_anchors(v))
+      end
+    end)
+  end
+
+  defp _merge_anchors(val) do
+    val
+  end
```
Comment (KamilLelonek) [inline lib/yaml_elixir/mapper.ex]: This can be a one-liner. No need to use redundant block.

**Review by KamilLelonek — CHANGES_REQUESTED** [review]
Please also extend the documentation. Otherwise, your feature will remain hidden from the others.

BTW. do you come from Ruby environment? You used lots of Ruby patterns in your code and very few Elixir ones.

**Comment by floriank** [comment]
Thanks for the review!

> do you come from Ruby environment? 

Yes, I work mostly in a ruby context throughout the day and used my lunch break for some elixir - guess the patterns bleed over when switching contexts :)

I will address your feedback shortly.

File: lib/yaml_elixir/mapper.ex (hunk 3 above)
Comment (floriank) [reply lib/yaml_elixir/mapper.ex]: I actually just followed the other function names inside this file, `maybe` kinda reminds me of Haskell's `Data.Maybe`, but, sure, I am all for not using the whole `_` notation.

**Review by KamilLelonek — APPROVED** [review]

**Comment by floriank** [comment]
:bow:

**Comment by dolfinus** [comment]
Hello.

Thank you for the contribution!

Just one question about this PR: why this new option `merge_anchors` was added?
I mean anchors are a part of RFC standard. A term `breaking changes` usually means that some behavior is described before become changed and this could lead to issues while updating a project dependency. But this wasn't an expected behavior in the first place. This is just a bug that has been fixed.
So is there any real need in this new option which allows package to return results not matching the YAML standard? And is there any need to make this option enabled by default?
