### PR TITLE
 Give functions which raise exceptions names ending with `!`

### LINKED ISSUE #22: Functions which raise expections should end with a bang
It's idiomatic in Elixir to have two versions of a function in the case that an error may occur:
- `Module.fun(...) :: {:ok, term} | {:error, term}`,
- `Module.fun!(...) :: term | no_return`.

At the moment there's no 'safe' version of the `YamlElixir.read_*` functions, so consumers must handle exceptions when reading arbitrary inputs. It's not necessarily desirable to "Let It Crash" when just reading a file - and exceptions don't pattern match nicely - so this behaviour should not be the default.

Adopting this proposal would result in a breaking API change, so the package minor version should be bumped.

### PR DESCRIPTION
**Pull request by samb1729**
Resolves #22 

This set of commits renames the existing functions, replacing them with safe alternatives which return idiomatic tuples.

I also removed a counter-intuitive `Mapper.process` code path which isn't exercised by the tests, and bumped the package version.

### CODE REVIEW

File: mix.exs [hunk 1]
```diff
@@ -4,7 +4,7 @@ defmodule YamlElixir.Mixfile do
   def project do
     [
       app: :yaml_elixir,
-      version: "1.3.2",
+      version: "1.4.0",
```
Comment (obmarg) [inline mix.exs:7]: Since this is a breaking change, shouldn't this be a major version bump?  To quote semver:

>  MAJOR version when you make incompatible API changes,
    MINOR version when you add functionality in a backwards-compatible manner, and
    PATCH version when you make backwards-compatible bug fixes.

Making this change in a minor version has broken my library that required `{:yaml_elixir, "~> 1.3"}`

Comment (KamilLelonek) [reply mix.exs:7]: Of course!

Comment (samb1729) [reply mix.exs:7]: Oh whoops, sorry about that.

Comment (samb1729) [reply mix.exs:7]: @KamilLelonek remedial action here is to bump the version to 2.0.0, push that package, then delete 1.4.0 from hex.pm (if hex allows that, otherwise revert and push 1.3.2 as 1.4.1).

Comment (KamilLelonek) [reply mix.exs:7]: OK, @ericmj is able to delete the package version. I'll contact him.
